version: '3'
services:
  db: 
    image: postgres:alpine
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}  
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: 
      always 
volumes:
  db_data: